worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Define a área de memória (keys_zone) e o caminho em disco para o cache
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=meu_cache:10m max_size=1g inactive=60m use_temp_path=off;

    upstream app1 {
        server app1:5000;
    }

    upstream app2 {
        server app2:3000;
    }

    server {
        listen 80;

        # Header customizado para facilitar o debug do cache (HIT, MISS, EXPIRED)
        add_header X-Cache-Status $upstream_cache_status;

        # Ignora headers de cache que as aplicações possam enviar, forçando o controle pelo Nginx
        proxy_ignore_headers Cache-Control Expires;

        location /app1/ {
            proxy_pass http://app1/;
            proxy_cache meu_cache;
            # Cache de 10 segundos para rotas com sucesso (200) da App1
            proxy_cache_valid 200 10s;
        }

        location /app2/ {
            proxy_pass http://app2/;
            proxy_cache meu_cache;
            # Cache de 1 minuto para rotas com sucesso (200) da App2
            proxy_cache_valid 200 1m;
        }
    }
}